### ISSUE TITLE
document why a service is better than an image

### ISSUE THREAD

**Issue by guillaume-d** [rocboronat/black-npe-live-wallpaper#4]
Please excuse the maybe vexing question, but why use this app, considering:
- it starts a service, which uses at least some RAM permanently AFAIK
- installing it eats some internal storage space (thanks for keeping it minimal though!)

...whereas using a non-live, image-based wallpaper with a 1x1 black image:
- does nothing of the above
- shouldn't consume any CPU resources AFAICU
- shouldn't use much RAM AFAICU

...unless Android has a harder time managing all the individual pixels / tiling so much? Maybe a say 32x32 or even a full-screen-size black image would fare better? (At least it would compress just as well on storage.)

Did someone measure how much RAM/CPU the app takes on real devices? (I know no good way for that at least on unrooted Android < 4.2, please advise.)
Did anyone compare with the black 1x1 image trick above?

If this app is just about making the setup easier (esp. WRT Android's wallpaper image tiling limitations), then https://github.com/AHelloWorldDev/MinimumWallpaper does only that already.

**Comment by rocboronat** [comment]
Hello @guillaume-d! Honestly, I never measured it. 10 years ago there was no other solution better than this app to just print a black background. https://github.com/AHelloWorldDev/MinimumWallpaper seems so easy! Love it :·)

Nowadays I think with the devices we have right now it doesn't care which system you want to use to have a black wallpaper. If it's black, OLED screens will save battery in case you spend a lot of time staring at the launcher background, and that's it.

**Comment by guillaume-d** [comment]
Thanks for answering, I was also asking because your app [is/has been](https://github.com/rocboronat/null-black-wallpaper/issues/2) on F-Droid, whereas the com.ahelloworlddev.minimumwallpaper one still is not, but one less app to have to keep is always good! :-)

**Comment by rocboronat** [comment]
Haha! It was a pleasure. Thanks for asking 😄

**Comment by goyalyashpal** [comment]
hi, yeah, so, my doubt is similar. 

* i have seen in 3 non-oled devices (coolpad from 2016, realme UI from 2020, and 2021) that their "super power saving" mode has black wallpaper too
* so that makes me wonder if there's any gain on system level too
* one possibility can be that the android flavour (aka ROM) has that thing as common functionality
* but still thought to share/ask, maybe there's some other reason as well....
